### ISSUE TITLE
$get() not working

### ISSUE THREAD

**Issue by mbajur** [klederson/ModelCore#20]
Hello! I'm playing around with ModelCore and i'm not able to make a simple GET query working. My service looks like that:

```
nemuApp.factory 'Places', (ModelCore) ->
  ModelCore.instance
    $type: 'Places'
    $pkField: 'id'
    $settings:
      urls:
        base: "/api/v1/places/:id"
```

`Places().$find()` works great and fires a request to `/api/v1/places/` but when i'm trying to use `Places().$get(1)`, the request is also fired to the same url and `id` segment is not included in it.

Can you advise me what am i possibiliy doing wrong? I'm using ModelCore from github master and angular 1.2.16

Thanks in advance
